import { 
    faGamepad, 
    faGlobeAmericas, 
    faSpinner,
    faCheck,
    faTimes,
    faCog,
    faFlagCheckered,
    faInfoCircle,
    faFrownOpen,
    faArrowLeft,
    faBars,
    faSave,
    faThumbsUp,
    faExclamationTriangle,
    faCodeBranch,
    faPlay,
    faPause,
    faSnowflake,
    faVideo,
} from "@fortawesome/free-solid-svg-icons"
import { 
    faJs, 
    faCss3, 
    faHtml5 
} from "@fortawesome/free-brands-svg-icons"

export default [
    faVideo,
    faSnowflake,
    faPause,
    faPlay,
    faCodeBranch,
    faExclamationTriangle,
    faThumbsUp,
    faSave,
    faBars,
    faArrowLeft,
    faFrownOpen,
    faInfoCircle,
    faFlagCheckered,
    faCog,
    faTimes,
    faCheck, 
    faGamepad,
    faGlobeAmericas,
    faJs,
    faCss3,
    faHtml5,
    faSpinner
]
