export const enum helperGameThreadCodes {
    acknowledgePing = 20_000
}

/* reverse map and union type generated by "generateReverseMaps.js", do not change */

export const helperGameThreadCodesReverseMap = {
	20_000: "acknowledgePing", 
} as const

export type HelperGameThreadCodes= keyof typeof helperGameThreadCodesReverseMap

/* generated by script end */