export const enum renderingThreadCodes {
    keyDownResponse = 10_000,
    keyUpResponse = 10_001,
    acknowledgePing = 10_002,
    respondToFatalError = 10_003,
    readyForRestart = 10_004
}

/* reverse map and union type generated by "generateReverseMaps.js", do not change */

export const renderingThreadCodesReverseMap = {
	10_000: "keyDownResponse", 
	10_001: "keyUpResponse", 
	10_002: "acknowledgePing", 
	10_003: "respondToFatalError", 
	10_004: "readyForRestart", 
} as const

export type RenderingThreadCodes= keyof typeof renderingThreadCodesReverseMap

/* generated by script end */