export const enum renderingThreadCodes {
    keyDownResponse = 10_000,
    keyUpResponse = 10_001,
    acknowledgePing = 10_002,
}

/* reverse map and union type generated by "generateReverseMaps.js", do not change */

export const renderingThreadCodesReverseMap = {
	10_000: "keyDownResponse", 
	10_001: "keyUpResponse", 
	10_002: "acknowledgePing", 
} as const

export type RenderingThreadCodes= keyof typeof renderingThreadCodesReverseMap

/* generated by script end */